# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Research
    url: research/
    weight: 20
  - name: Vitae
    url: vitae/
    weight: 30
  - name: Teaching
    url: teaching/
    weight: 40
  - name: References
    url: references/
    weight: 50
  - name: Contact
    url: contact/
    weight: 70
#  - name: Blog
#    url: '/blog/'
#    weight: 60
 # - name: CV
 #   url: '/files/cv.pdf'
 #   weight: 70
  
# Sub-home menu
#  - name: About
#    url: '#about'
#    parent: " "
#    weight: 50
#  - name: Background
#    url: '#cv'
#    parent: " "
#    weight: 60
#  - name: Recent Publications
#    url: '#publications'
#    parent: " "
#    weight: 70  
#  - name: Recent Blog Posts
#    url: '#posts'
#    parent: " "
#    weight: 80
#  - name: Contact
#    url: '#contact'
#    parent: " "
#    weight: 90

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
