baseURL: "https://serkankocabas.github.io" 
title: Serkan Kocabas
theme: PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true
paginate: 20


taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: /papers/
          weight: 1
        - name: Vitae
          url: /courses/
          weight: 2
        - name: Teaching
          url: /design/
          weight: 3        
        - name: References
          url: /tags/
          weight: 4
        - name: Contact
          url: /archive/
          weight: 5

params:
    description: "This website hosts Pascal Michaillat's research papers, course materials, design templates, curriculum vitae, and contact information."
    author: Serkan Kocabas
    googleAnalyticsID: ""
    images: ["cover.png"]
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers","courses","design"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Serkan Kocabas
          subtitle: "I am an economist currently pursuing my Ph.D. in Economics at Universidad Carlos III de Madrid while working as a Ph.D. trainee at the European Central Bank. Prior to my doctoral studies, I gained valuable experience as an Economist at BBVA-Research. I completed my Master of Research in Economic Analysis at Universidad Carlos III de Madrid. Additionally, I hold a Master of Science in Macroeconomic Policy and Financial Markets from the Barcelona School of Economics, and I obtained my bachelor’s degree in Economics from Middle East Technical University. My research focuses on Fiscal and Monetary policies, International Macro, and Quantitative Macro, with a current emphasis on climate change and firm heterogeneity."
          imageUrl: "/picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research
              url: /papers/
            - name: Vitae
              url: /courses/
            - name: Teaching
              url: /design/
            - name: References
              url: /tags/
            - name: Contact
              url: /archive/

    socialIcons:
        - name: CV
          url: /cv.pdf
        - name: Email
          url: mailto:skocabas@eco.uc3m.es
        - name: Location
          url: /location/
        - name: Office Hours
          url: /officehours/
        - name: Google Scholar
          url: 
        - name: Twitter
          url: https://x.com/serkankocabas26
        - name: GitHub
          url: https://github.com/serkankocabas

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Pascal Michaillat"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

titleCaseStyle: 'none'
