baseURL: "https://serkankocabas.github.io" 
title: Serkan Kocabaş
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name:References
          url: books/
          weight: 5 
        - name: Research
          url: papers/
          weight: 2
        - name: Vitae
          url: courses/
          weight: 3
        - name: References
          url: data/
          weight: 4 
        - name: Contact
          url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
          weight: 6

params:
    description: "I am a Professor of Philology at the Institute of Romance Philology in Regensburg, Germany. My research focuses mostly on Portuguese irregular verbs."
    author: Serkan Kocabaş
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Serkan Kocabaş
          subtitle: "I am an economist currently pursuing my Ph.D. in Economics at Universidad Carlos III de Madrid while working as a Ph.D. trainee at the European Central Bank. Prior to my doctoral studies, I gained valuable experience as an Economist at BBVA-Research. I completed my Master of Research in Economic Analysis at Universidad Carlos III de Madrid. Additionally, I hold a Master of Science in Macroeconomic Policy and Financial Markets from the Barcelona School of Economics, and I obtained my bachelor's degree in Economics from Middle East Technical University.

My research focuses on Fiscal and Monetary policies, International Macro, and Quantitative Macro, with a current emphasis on climate change and firm heterogeneity."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research
              url: papers/
            - name: Vitae
              url: courses/
            - name: Teaching
              url: data/
            - name: References
              url: books/
            - name: Contact
              url: tags/


    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:skocabas@eco.uc3m.es
        - name: Zoom
          url: https://us05web.zoom.us/j/*******331?pwd=WlBRbG9Qb3c4SDVJenZTeStzeFR5QT09
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        - name: GitHub
          url: https://github.com/serkankocabas
        - name: Substack
          url: https://pmichaillat.substack.com
        - name: YouTube
          url: https://www.youtube.com/@alexandermccallsmithoffici9000
        - name: Twitter
          url: https://x.com/serkankocabas26

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Serkan Kocabaş"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2