name: Build and Deploy Hugo Site
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Hugo Extended
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: '0.119.0'
        extended: true
    - name: Build
      run: hugo --minify
    - name: Deploy
      run: ./deploy.sh